from pathlib import Path
from config.settings import AGENT_ROOT, DATA_DIR, RAG_DIR, OUTPUTS_DIR, LOG_DIR

DATA_PATH = AGENT_ROOT / DATA_DIR
MOCK_DIR = DATA_PATH / "mock"
RAG_PATH = AGENT_ROOT / RAG_DIR
PROMPTS_DIR = AGENT_ROOT / "prompts"
INPUTS_DIR = AGENT_ROOT / "inputs"
OUTPUTS_PATH = AGENT_ROOT / OUTPUTS_DIR
LOGS_PATH = AGENT_ROOT / LOG_DIR

RESPUESTAS_JSON_DIR = OUTPUTS_PATH / "respuestas_json"
BORRADORES_DIR = OUTPUTS_PATH / "borradores"
INFORMES_DIR = OUTPUTS_PATH / "informes"

for ruta in [DATA_PATH, MOCK_DIR, RAG_PATH, OUTPUTS_PATH, RESPUESTAS_JSON_DIR, BORRADORES_DIR, INFORMES_DIR, LOGS_PATH]:
    ruta.mkdir(parents=True, exist_ok=True)
