from config.settings import _bool

# Permisos operativos. En MVP deben estar cerrados por defecto.
ALLOW_SEND_TELEGRAM = _bool("ALLOW_SEND_TELEGRAM", "false")
ALLOW_BACKEND_READ = _bool("ALLOW_BACKEND_READ", "true")
ALLOW_BACKEND_WRITE = _bool("ALLOW_BACKEND_WRITE", "false")
ALLOW_REGISTER_COMMUNICATION = _bool("ALLOW_REGISTER_COMMUNICATION", "true")
ALLOW_CREATE_INCIDENTS = _bool("ALLOW_CREATE_INCIDENTS", "true")
ALLOW_NOTIFY_ADMIN = _bool("ALLOW_NOTIFY_ADMIN", "true")

# Acciones críticas: siempre False en MVP salvo decisión explícita del equipo.
ALLOW_CONFIRM_TRAVEL = _bool("ALLOW_CONFIRM_TRAVEL", "false")
ALLOW_APPROVE_DOCUMENTS = _bool("ALLOW_APPROVE_DOCUMENTS", "false")
ALLOW_CHANGE_EVENT_DATA = _bool("ALLOW_CHANGE_EVENT_DATA", "false")
ALLOW_MASS_MESSAGES = _bool("ALLOW_MASS_MESSAGES", "false")
ALLOW_AUTO_APPROVAL = _bool("ALLOW_AUTO_APPROVAL", "false")
ALLOW_DB_WRITE = _bool("ALLOW_DB_WRITE", "false")
ALLOW_EXTERNAL_SEND = _bool("ALLOW_EXTERNAL_SEND", "false")
ALLOW_CREATE_EVENT = _bool("ALLOW_CREATE_EVENT", "false")

# Escalado humano.
ESCALATE_UNKNOWN_SPEAKER = _bool("ESCALATE_UNKNOWN_SPEAKER", "true")
ESCALATE_MULTIPLE_ACTIVE_EVENTS = _bool("ESCALATE_MULTIPLE_ACTIVE_EVENTS", "true")
ESCALATE_MISSING_DATA = _bool("ESCALATE_MISSING_DATA", "true")
ESCALATE_LOW_CONFIDENCE = _bool("ESCALATE_LOW_CONFIDENCE", "true")
